//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperAdminConsole.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ecommerce@3dcondox.com")]
        public string emailFrom {
            get {
                return ((string)(this["emailFrom"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("kharkov141159")]
        public string emailPwd {
            get {
                return ((string)(this["emailPwd"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int serverRequestTimeoutSec {
            get {
                return ((int)(this["serverRequestTimeoutSec"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("49.99")]
        public decimal PriceOf3DListing {
            get {
                return ((decimal)(this["PriceOf3DListing"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13")]
        public decimal SalesTaxValuePercent {
            get {
                return ((decimal)(this["SalesTaxValuePercent"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9.99")]
        public decimal ChangeViewOrderOptionsFee {
            get {
                return ((decimal)(this["ChangeViewOrderOptionsFee"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("adminan")]
        public string clientLogin {
            get {
                return ((string)(this["clientLogin"]));
            }
            set {
                this["clientLogin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("smelatoronto")]
        public string clientPassword {
            get {
                return ((string)(this["clientPassword"]));
            }
            set {
                this["clientPassword"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://vrt.3dcondox.com/")]
        public string serverEndPoint {
            get {
                return ((string)(this["serverEndPoint"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int defaultDaysValidTemp {
            get {
                return ((int)(this["defaultDaysValidTemp"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3D Condo Explorer team\r\nwww.3dcondox.com\r\nsales@3DcondoX.com\r\n1-855-332-6630 x.2\r" +
            "\n")]
        public string defaultSignature {
            get {
                return ((string)(this["defaultSignature"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("365")]
        public int defaultDaysValidPermanent {
            get {
                return ((int)(this["defaultDaysValidPermanent"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"We created an Interactive 3D Listing for your {MLS_NUMBER}:
        {VIEWORDER_URL}
This link will die in {DAYS_VALID} days. If you want to keep it, send email to sales@3DcondoX.com.
For more info see http://youtu.be/rTLzjlY8HjM
  Thanks, 3dcondox.com
")]
        public string the300charsTemplate {
            get {
                return ((string)(this["the300charsTemplate"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("On your listing {VIEWORDER_ADDRESS}")]
        public string defaultPromoSubject {
            get {
                return ((string)(this["defaultPromoSubject"]));
            }
            set {
                this["defaultPromoSubject"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"PLEASE DO NOT REPLY TO THIS MESSAGE.

Dear {ADDRESS_TO},
Thank you for ordering from 3D Condo Explorer Inc!

Here are your order details:
---------------------------
    Order Number: {PAYMENT_REF}
    Order Date: {TODAYS_DATE} 
    {PRODUCT_NAME} Address:
        {VIEWORDER_ADDRESS}

You cannot change address of the {PRODUCT_NAME}, but other options can be changed
at any time

Interactive 3D Listing URL:
    {VIEWORDER_URL}
    Please copy-paste this link to use in your MLS listing.

(Note: this Interactive 3D Listing will be valid for {DAYS_VALID} days. You can extend this term any time,
as many times as you want free of charge - by calling Customer Support 1-855-332-6630 ext.2).

Price:    ${PRICE_NO_TAX}
HST:      ${TAX}
-------------------
Total:    ${PAID_GROSS}


We hope you enjoy your purchase!

Sincerely, 

The 3D Condo Explorer Sales Team")]
        public string orderConfirmationTemplate {
            get {
                return ((string)(this["orderConfirmationTemplate"]));
            }
            set {
                this["orderConfirmationTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Dear {ADDRESS_TO},

I noticed that you posted an MLS listing {MLS_NUMBER}for the 
    {VIEWORDER_ADDRESS}

3D Condo Explorer has created an Interactive 3D Listing for this property.
Interactive 3D Listing is a new amazing way of presenting your real estate using the
3D Virtual Reality world of Google Earth - check this video to get the idea
http://youtu.be/rTLzjlY8HjM...

So, here is your Interactive 3D Listing - click it to see how it works:

   {VIEWORDER_URL}

IMPORTANT NOTE: The link above is temporary, if you do nothing, it'll die in {DAYS_VALID} days.
So, IF YOU WANT TO KEEP IT, PLEASE COPY THIS MESSAGE AND SEND IT TO sales@3DcondoX.com.

For more info visit our website (www.3dcondox.com), or call us at:
    1-855-332-6630 (1-855-3d cond0) ext.2 (""Sales and Marketing""), 9AM-5PM weekdays
Also you can just email your questions to sales@3DcondoX.com

We are glad to help you with your highly competitive and challenging business.

Yours,
{SIGNATURE}
{TODAYS_DATE}")]
        public string listingPromoTemplate {
            get {
                return ((string)(this["listingPromoTemplate"]));
            }
            set {
                this["listingPromoTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Interactive 3D Listing Order Confirmation")]
        public string defaultConfirmationSubject {
            get {
                return ((string)(this["defaultConfirmationSubject"]));
            }
            set {
                this["defaultConfirmationSubject"] = value;
            }
        }
    }
}
